version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # RabbitMQ service
      - "15672:15672"   # RabbitMQ web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  order-service:
    build:
      context: ./OrderService
    container_name: order-service
    ports:
      - "5001:80"
    depends_on:
      - rabbitmq
